### ISSUE TITLE
UNO - preprocessing can't find config file

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/Singularity#107]
Command: `singularity run build/Uno.sif preprocess.sh /candle_data_dir -h`
Host: lambda
Container: build from develop branch

```
wilke@lambda7:~/IMPROVE/Singularity$ singularity run build/Uno.sif preprocess.sh /candle_data_dir -h
CMD = python /usr/local/Benchmarks/Pilot1/Uno_IMPROVE//uno_preprocess_improve.py --config_file -h
using IMPROVE_DATA_DIR /candle_data_dir
using CANDLE_CONFIG
running command python /usr/local/Benchmarks/Pilot1/Uno_IMPROVE//uno_preprocess_improve.py --config_file -h
2023-12-19 21:30:46.018880: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-19 21:30:46.430029: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Importing candle utils for Keras
Traceback (most recent call last):
  File "/usr/local/Benchmarks/Pilot1/Uno_IMPROVE//uno_preprocess_improve.py", line 492, in <module>
    main(sys.argv[1:])
  File "/usr/local/Benchmarks/Pilot1/Uno_IMPROVE//uno_preprocess_improve.py", line 477, in main
    params = frm.initialize_parameters(
  File "/usr/local/IMPROVE/improve/framework.py", line 591, in initialize_parameters
    frm = ImproveBenchmark(
  File "/usr/local/lib/python3.8/dist-packages/candle/benchmark_def.py", line 71, in __init__
    raise Exception(
Exception: ERROR ! Required default configuration file not available.  File /candle_data_dir/uno_default_model.txt ... Exiting
```

**Comment by wilke** [comment]
UNO is failing basic tests. Transferring this issue to the Benchmark repo.

Please fix the use of `filepath` in the preprocess script. Should behave the same way as in the train script. In addition clean up the multiple redundant value assignments for `filepath`.
