### ISSUE TITLE
Test TGSA

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/Singularity#52]
Command:

1.  `train.sh 1 ./tmp`
2. `singularity run --bind `pwd`/tests:/candle_data_dir --nv build/TGSA.sif train.sh 4 /candle_data_dir --epochs 1`

Status: In progress

Depends on:
- #33  
- https://github.com/JDACS4C-IMPROVE/TGSA/pull/2
- #53 
- https://github.com/JDACS4C-IMPROVE/TGSA/issues/3
- https://github.com/JDACS4C-IMPROVE/TGSA/issues/4
- https://github.com/JDACS4C-IMPROVE/TGSA/issues/5

Output:

1:
```
  File "/homes/wilke/miniconda3/envs/TGSA/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/homes/wilke/miniconda3/envs/TGSA/lib/python3.6/site-packages/torch_sparse/__init__.py", line 28, in <module>
    f'Detected that PyTorch and torch_sparse were compiled with '
RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_sparse has CUDA version 11.4. Please reinstall the torch_sparse that matches your PyTorch install.
```

**Comment by wilke** [comment]
Command: `singularity run --nv --bind `pwd`/tmp:/candle_data_dir build/TGSA.sif train.sh 1 /candle_data_dir --epochs 1`
Status: **Failed**

Output:
```
CMD = python /usr/local/TGSA/candle_train.py --epochs 1
/usr/local/TGSA/train.sh: line 59: ./candle_glue.sh: No such file or directory
using original data placed in /candle_data_dir
/candle_data_dir//Data
/usr/local/TGSA/train.sh: line 77: ./candle_glue.sh: No such file or directory
using original data placed in /candle_data_dir//Data
using CUDA_VISIBLE_DEVICES 1
...

 'weight_path': ''}
Training on Pilot1 dataset
Traceback (most recent call last):
  File "/usr/local/TGSA/candle_train.py", line 205, in <module>
    main()
  File "/usr/local/TGSA/candle_train.py", line 202, in main
    run(gParams)
  File "/usr/local/TGSA/candle_train.py", line 111, in run
    os.makedirs(output_root_dir)
  File "/opt/conda/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/usr/local/TGSA/benchmark_dataset_generator/improve_data_dir'
```

**Comment by wilke** [comment]
Command works but not printing IMPROVE_RESULT

**Comment by RylieWeaver** [comment]
Fixed and pull requested to improve branch

**Comment by wilke** [comment]
Starting over for next release cycle.
